/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.telas;

import com.mycompany.bd.MemoryDatabase;
import com.mycompany.outros.Formularios;
import com.mycompany.outros.Temp;
import com.mycompany.produto.Produto;
import java.awt.Point;
import java.util.ArrayList;
import java.util.List;
import java.util.NoSuchElementException;
import java.util.Optional;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;

/**
 *
 * @author 10156
 */
public class ListProduto extends javax.swing.JFrame {

    /**
     * Creates new form ListProduto
     */
    public ListProduto() {
        initComponents();
        
        setLocationRelativeTo(null);
        
        listar(MemoryDatabase.listaProdutos);
    }

    public void listar(ArrayList<Produto> lista){
        for(Produto p : lista){
            jtaListProduto.append(p.toString() + "\n");
        }
    };
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtfFiltro = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaListProduto = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jcbFiltro = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jtaListProduto.setColumns(20);
        jtaListProduto.setRows(5);
        jtaListProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtaListProdutoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtaListProduto);

        jButton1.setText("Filtrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jcbFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "DESCRIÇÃO", "PREÇO MAIOR OU IGUAL A", "PREÇO MENOR OU IGUAL A" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jcbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfFiltro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jcbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        Formularios.listProduto = null;
    }//GEN-LAST:event_formWindowClosed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//        Optional<Produto> prod = BD.listaProdutos.stream().filter(p -> p.getId() == Integer.valueOf(jtfFiltro.getText())).findFirst();
        
        List<Produto> produtosFiltrados = null; 

        Optional<Produto> prod = null;
        
        try{
            switch (jcbFiltro.getSelectedIndex()) {
                case 0:
                    produtosFiltrados = MemoryDatabase.listaProdutos.stream()
                        .filter(p -> p.getId() == Integer.parseInt(jtfFiltro.getText()))
                        .collect(Collectors.toList());
                    break;
                case 1:
                    produtosFiltrados = MemoryDatabase.listaProdutos.stream()
                        .filter(p -> p.getDescricao().contains(jtfFiltro.getText()))
                        .collect(Collectors.toList());
                    break;
                case 2:
                    produtosFiltrados = MemoryDatabase.listaProdutos.stream()
                        .filter(p -> p.getPreco() >= Double.parseDouble(jtfFiltro.getText()))
                        .collect(Collectors.toList());
                    break;
                case 3:
                    produtosFiltrados = MemoryDatabase.listaProdutos.stream()
                        .filter(p -> p.getPreco() <= Double.parseDouble(jtfFiltro.getText()))
                        .collect(Collectors.toList());
                    break;
            }
            
            jtaListProduto.setText("");
            for(Produto p : produtosFiltrados){
                jtaListProduto.append(p.toString() + "\n");
            }
        }catch(NoSuchElementException e){
            JOptionPane.showMessageDialog(null, "Elemento não encontrado.");
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Digite um valor numérico.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtaListProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtaListProdutoMouseClicked
        try{
            Point pontoCique = evt.getPoint();
            int posCursor = jtaListProduto.viewToModel(pontoCique);
            int linha = jtaListProduto.getLineOfOffset(posCursor);

            System.out.println("Clicked on line: " + linha);
            
            Produto selProd = MemoryDatabase.listaProdutos.get(linha);
            
            Temp.tempObj = selProd;
            
            JOptionPane.showMessageDialog(null, (Produto) Temp.tempObj);
            
            if(Formularios.cadProduto == null){
                CadProduto cadProduto = new CadProduto();
                Formularios.cadProduto = cadProduto;
                Formularios.cadProduto.setVisible(true);
                
                ((CadProduto) Formularios.cadProduto).verificarDadosTemporarios();
            }else{
                Formularios.cadProduto.setVisible(true);
                ((CadProduto) Formularios.cadProduto).verificarDadosTemporarios();
            }
        }catch(Exception e){
        
        }
    }//GEN-LAST:event_jtaListProdutoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbFiltro;
    private javax.swing.JTextArea jtaListProduto;
    private javax.swing.JTextField jtfFiltro;
    // End of variables declaration//GEN-END:variables
}
